import { generateText } from "ai";
import { google } from "@ai-sdk/google";
import { uploadImage } from "@/app/actions/uploads/uploadImage";

export const maxDuration = 60;

// Helper to convert base64 to File for upload
function base64ToFile(
  base64Data: string,
  filename: string = "generated.png"
): File {
  const buffer = Buffer.from(base64Data, "base64");
  const blob = new Blob([buffer], { type: "image/png" });
  return new File([blob], filename, { type: "image/png" });
}

type GenerateVariantImageInput = {
  sourceImageUrl: string;
  variantTitle: string;
  imagePrompt: string;
};

type GenerateVariantImageResult = {
  success: boolean;
  imageUrl?: string;
  error?: string;
};

export async function POST(req: Request): Promise<Response> {
  try {
    const input: GenerateVariantImageInput = await req.json();

    const { sourceImageUrl, variantTitle, imagePrompt } = input;

    if (!sourceImageUrl) {
      return Response.json(
        { success: false, error: "Source image URL is required" },
        { status: 400 }
      );
    }

    console.log("Generating variant image:", { variantTitle, imagePrompt });

    // Build the prompt for Gemini
    const prompt = `${imagePrompt}

IMPORTANT INSTRUCTIONS:
- Use the provided product image as reference
- Modify ONLY the specified attributes (color, material, etc.)
- Keep all other product details identical (shape, size, features, design)
- Pure white background (#FFFFFF)
- No shadows, no floor, no environment
- Clean product shot style, centered composition
- Front view perspective
- Professional e-commerce product photography style`;

    const imageResult = await generateText({
      model: google("gemini-2.5-flash-image"),
      messages: [
        {
          role: "user",
          content: [
            {
              type: "text",
              text: prompt,
            },
            {
              type: "image" as const,
              image: sourceImageUrl,
            },
          ],
        },
      ],
    });

    // Find the generated image in result.files
    const generatedImage = imageResult.files?.find((file) =>
      file.mediaType.startsWith("image/")
    );

    if (!generatedImage) {
      console.error("No image generated by Gemini");
      return Response.json({
        success: false,
        error: "Failed to generate image",
      } satisfies GenerateVariantImageResult);
    }

    // Convert Uint8Array to base64
    const base64 = Buffer.from(generatedImage.uint8Array).toString("base64");

    // Upload to GCS
    const file = base64ToFile(base64, `variant-${variantTitle.toLowerCase().replace(/\s+/g, "-")}.png`);
    const uploadedUrl = await uploadImage(file, "variant-images");

    console.log("Variant image generated and uploaded:", uploadedUrl);

    return Response.json({
      success: true,
      imageUrl: uploadedUrl,
    } satisfies GenerateVariantImageResult);
  } catch (error) {
    console.error("Variant image generation error:", error);
    return Response.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Failed to generate variant image",
      } satisfies GenerateVariantImageResult,
      { status: 500 }
    );
  }
}
